### PR TITLE
Remove obsolete packages, add Gen3 Lite Support

### PR DESCRIPTION
**Pull request by civerachb-cpr**

### CODE REVIEW

**Comment by dniewinski** [comment]
Untested by me, but looks good

**Review by dniewinski — APPROVED** [review]

**Comment by dniewinski** [comment]
Please correct the references to dingo

**Comment by civerachb-cpr** [comment]
The only one I could see that I'd missed was in the license file. Was there another that you found?

**Comment by dniewinski** [comment]
Just the one

**Pull request merged**
